### ISSUE TITLE
How do you install this package?

### ISSUE THREAD

**Issue by leverarch-app** [michaeldzjap/react-pdf-sample#4]
This might be really simple but after I’ve run npm run dev...what happens next? Maybe I am used to running create React app too much.

**Comment by michaeldzjap** [comment]
`npm run dev` (or `npm run prod` for that matters) should create a _/dist_ folder with inside it an _index.html_. You have to serve this _index.html_ with a web server though, otherwise PDF's won't load. So assuming you use [http-server](https://github.com/http-party/http-server) you run `http-server ./dist` if you are located in the parent folder and then visit http://localhost:8080 in your browser. That should do the trick.
